<?php

namespace AppBundle\Repository;

/**
 * RondaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RondaRepository extends \Doctrine\ORM\EntityRepository
{
}
