user:
    resource: "@UserBundle/Resources/config/routing.yml"

app.index:
    resource: "@AppBundle/Controller/IndexController.php"
    type: annotation

app.liga:
    resource: "@AppBundle/Controller/LigaController.php"
    type: annotation
    prefix: /liga

app.equipo:
    resource: "@AppBundle/Controller/EquipoController.php"
    type: annotation
    prefix: /equipo

app.jugador:
    resource: "@AppBundle/Controller/JugadorController.php"
    type: annotation
    prefix: /jugador

app.entrenador:
    resource: "@AppBundle/Controller/EntrenadorController.php"
    type: annotation
    prefix: /entrenador

app.ronda:
    resource: "@AppBundle/Controller/RondaController.php"
    type: annotation
    prefix: /ronda

app.partido:
    resource: "@AppBundle/Controller/PartidoController.php"
    type: annotation
    prefix: /partido